### ISSUE TITLE
“Lineage Version” issue.

### ISSUE THREAD

**Issue by JunASAKA** [AndyCGYan/lineage_build_unified#12]
Hey there!
   I’ve just built the Lineage OS 18.1 treble with your unified building script. But I noticed that the “Lineage Version” shows “lineage-18.1-20211117-UNOFFICIAL-” instead of “ lineage-18.1-20211117-UNOFFICIAL-treble” in settings (also in build.prop).
   As my experience, the device name, which is “treble” in this project, should be shown in the foot of lineage version. But it didn’t work like that, which makes me confused. Consequently, I’m wondering whether it’s a mistake of phh device tree or something went wrong with the source code.
   Is this problem also occurs in your build or it just took place on account of my personal slip? I would sincerely appreciate it if you could deal with this problem for us.
   Looking forward to your early reply.

Thanks and Regards,
Jun ASAKA.

**Comment by AndyCGYan** [comment]
Should be trivial to fix, but I never thought someone would actually need that...

**Comment by AndyCGYan** [comment]
Okay, this is not as trivial as I thought, but exposes a problem I've been solving the wrong way from day-1.
PHH's generate.sh generates target makefiles, but LOS expects them to be named `lineage_*.mk`, and if not, fails to set `LINEAGE_BUILD`, which makes a couple of checks thinks we're not building LOS, including a crucial sepolicy makefile include, and several APN includes. From day-1 I've manually included/fixed those, but it seems the correct way is to just fix the names of target makefiles, which should also remove the need for the aforementioned fixes. Let me test and get back to you later.

**Comment by AndyCGYan** [comment]
Working, pushed. ![Screenshot_20211118-190832_Settings](https://user-images.githubusercontent.com/18655204/142412305-09957448-afa9-45f3-a3e0-4c12557289bb.png)
The [actual fix commit](https://github.com/AndyCGYan/lineage_patches_unified/blob/lineage-18.1/patches_treble/device_phh_treble/0001-treble-Proper-target-names-for-LineageOS.patch) should be good to PR to PHH's device_phh_treble globally, but just in case it breaks stuff in unexpected ways, I'll give it a month's grace period.

**Comment by JunASAKA** [comment]
Thanks a lot for paying attention to my comments and I am more than delighted to make contributions to the Open-Source causes. Cheerful to cooperate!
