### ISSUE TITLE
Question: is it possible to resize system

### ISSUE THREAD

**Issue by feduss** [AndyCGYan/lineage_build_unified#16]
Hi! My chinese tablet (aonly, vndk 27) has a 1.1gb system partition, and the treble_arm_AvS is too big (1.2gb)...is it possible to remove extra stuff, such as font?

I'm asking for 17.1 because i don't think that 18.1 is too much compatible with android 8.1 vendor

**Comment by AndyCGYan** [comment]
If as simple as 32A is too big for you then I'm afraid you don't have much of a choice; I no longer build Q either. PHH's AOSP might suit you better.
