### ISSUE TITLE
Feature request: provide bvN build

### ISSUE THREAD

**Issue by ivysrono** [AndyCGYan/lineage_build_unified#17]
I don't want root with PHH Superuser.

**Comment by AndyCGYan** [comment]
Securize in PHH Settings, or make your own pre-Securized build with [sas-creator](https://github.com/phhusson/sas-creator). I'm not really open to adding more public variants.

**Comment by ivysrono** [comment]
> Securize in PHH Settings.

https://github.com/phhusson/treble_experimentations/issues/2203

**Comment by AndyCGYan** [comment]
Work with PHH on that then. Or if you just want Magisk, unlike PHH's AOSP, you can just use it on mine without Securizing (ignore the "abnormal SU" message from Magisk).
