### ISSUE TITLE
thank you ♥️ and ..

### ISSUE THREAD

**Issue by src1a** [AndyCGYan/lineage_build_unified#21]
I really enjoy the pixel experience. Thanks guys, the problem of turning on the phone was solved by double-tapping the a307fn (a30s), Thank you ❤️

And ..

A few questions and minor problems

1. Why was the search box and game dashboard removed in the settings section?

2. The effect when deleting the charge is deleted like new playing

3. No change from the music player in the status bar in the new version

.. ..

At root / system / bin / rw-system.sh this part setprop setprop ro.surface_flinger.use_color_management true Set true to default so that we do not activate it manually every time ..

I suggest that in the phh settings section of the customization future section of the family font section, you put an option to load our favorite font for this device.

I'm sorry if I have a grammatical mistake, my English is not very good, #GoogleTranslate

**Comment by AndyCGYan** [comment]
You sure you're in the right place? This is no PixelExperience, and LOS with GAPPS build is far from "Pixel experience"...

**Comment by src1a** [comment]
Of course I am, I saw this feature in other versions of gsi, so I informed you

**Comment by AndyCGYan** [comment]
Q1 is GAPPS-related, which I can't/won't answer.
Q2/3 I can't quite understand what you're saying.
For color management, if you have a reason to enable it and perceptible proof that it works, let one of us know and we might enable it for just this device. Does a low-mid-end device like this even have a selective-mode display though...?
Fonts and other features - in general, PHH opts to not add arbitrary features into his AOSP, and I do similarly in LOS. If you're into fonts, Magisk modules might be a better (perhaps more error-proof too) entrypoint.

It does still baffle me that you keep referring to this as "pixel experience" - you sure you aren't referring to the "legit" PixelExperience by @ponces ?

**Comment by src1a** [comment]
I'm talking about this custom ROM made by ponces. Is the address file I gave. I manually activate it again after each update. It is better to activate it by default, even after activation, for reasons I do not know, the device will start faster!

This option is not enabled by default




![Screenshot_20220322-221003_Settings.png](https://user-images.githubusercontent.com/101948233/159542374-7dfb81fd-bdab-4621-ab61-b35f41d38e98.png)

**Comment by AndyCGYan** [comment]
Then talk to him, not me.
