### ISSUE TITLE
Not work live wallpaper

### ISSUE THREAD

**Issue by src1a** [AndyCGYan/lineage_build_unified#22]
Live wallpaper does not work in this version, please fix it

**Comment by AndyCGYan** [comment]
You aren't even using LOS, why are you still here...?

**Comment by src1a** [comment]
Sorry it was in save mode it works now
What do you mean by LOS? I am using a custom pixel ROM

**Comment by src1a** [comment]
Lineageos?

**Comment by src1a** [comment]
Where can I find the owner page of this ROM? I enter this page when I want to ask a question

**Comment by AndyCGYan** [comment]
PE has its own [Telegram support channel](https://t.me/pixelexperiencegsi).
