### ISSUE TITLE
Hello. I have a problem with self builded image

### ISSUE THREAD

**Issue by giga-bytes-dev** [AndyCGYan/lineage_build_unified#23]
Hello. I have a problem with self builded treble img with https://github.com/AndyCGYan/lineage_build_unified (https://github.com/AndyCGYan/lineage_build_unified). (lineage os 18.1)

I build img and write it to phone with fastboot and phone no boot. But then i flash image from https://sourceforge.net/projects/andyyan-gsi/files/lineage-18.x/, system boots and works. I dont know why self builded firmware no works.

**Comment by giga-bytes-dev** [comment]
AndyCGYan image  lineage-18.1-20220315-UNOFFICIAL-arm64_bvS.img  1.75 gigabyte
My image lineage-18.1 1.15 gigabyte (some no included while build)?

**Comment by AndyCGYan** [comment]
Upload the image somewhere for inspection?

**Comment by giga-bytes-dev** [comment]
https://gofile.io/d/HLlWNq  build logs.

https://gofile.io/d/KEq4ac builded image


I use ccache for fast build(rebuild). I will try build without ccache today too.

**Comment by AndyCGYan** [comment]
I immediately noticed - a64 (A64B) != arm64 (64B).

ccache is OK to use.
