### ISSUE TITLE
Clarify Build Wiki

### ISSUE THREAD

**Issue by scotthep** [AndyCGYan/lineage_build_unified#24]
bash lineage_build_unified/buildbot_unified.sh treble A64B A64BG 64B 64BG

I would like to build an ARM64 vanilla image per the description on sourceforge:
{arm|a64|arm64}_{a|b}{v|g}{N|S}-{vndklite|personal}
|               |    |    |     |
|               |    |    |     vndklite: VNDKLite & read-writeable /system
|               |    |    |     personal: Build with personal mods, for reference
|               |    |    |
|               |    |    N: No Superuser
|               |    |    S: With PHH Superuser (app needed)
|               |    |
|               |    v: Vanilla, i.e. no GAPPS
|               |    g: With GAPPS
|               |
|               a: "A-only", i.e. system-as-system (deprecated since Android 12)
|               b: "AB", i.e. system-as-root
|
arm: ARM 32-bit (deprecated since Android 12)
a64: ARM 32-bit with 64-bit binder
arm64: ARM 64-bit

Is the invocation ARM64B or 64B?

I also interested in my build supporting Bromite webview in my build.
https://github.com/bromite/bromite/wiki/Installing-SystemWebView
phh Treble_experimentations had added the necessary xml entry.  Is it entered in your code base and if not, what would be the best entry point (patch your code base or import phh patch under the phh patch directory)?

Thanks for providing your builds

**Comment by AndyCGYan** [comment]
A64B = a64, 64B = arm64.

You know I don't do FLOSS, but supposedly it's as simple as including PHH's FLOSS sub-manifest, then changing the build target to xxx_b**f**S. Unfortunately that's as far as I'll help you on this.
