### ISSUE TITLE
what exactly does option remove telephone subsystem

### ISSUE THREAD

**Issue by otpisani** [AndyCGYan/lineage_build_unified#25]
Hello,

Can someone help me, like to understood what exactly does mention command under misc option in lineageOS, if I decompile TrebleApp.apk  I can find exactly string remove_telephony_subsystem with hex or binary number 0x7f0d0023 or 2131558435.

Robin

**Comment by AndyCGYan** [comment]
For PHH Settings-related stuff, [ask him instead](https://github.com/phhusson/treble_experimentations/issues), I include the app verbatim.
