### ISSUE TITLE
Safetynet not passed

### ISSUE THREAD

**Issue by thefiredragon** [AndyCGYan/lineage_build_unified#26]
Is there a way to fix safetynet pass?

This builds break safteynet also selinux is disabled,
PE GSI has not this issue
Best regards
Dan

**Comment by AndyCGYan** [comment]
"This build"? If you're sure it's May's LOS19.1 build that regressed compared to April's, it might be because of some stuff I just added; otherwise I wouldn't know.

As a Chinese I can't offer further help on GAPPS/SN topics either, try XDA/TG and help each other out.

**Comment by thefiredragon** [comment]
I had first tried last build from your sourceforge repo, and builded own 64AB image with your repo, when you try an app like safetynet test from app store, safteynet is broken ..

I could install magisk to solve this but personally I don't like to root my device. So google pay and other banking apps won't work. Think it's not a Gapps issue

**Comment by AndyCGYan** [comment]
Hi, 10 days have passed and you still haven't gotten back to be about what I asked - **whether it's precisely the May build that broke your SN**. As we're getting close to the June build, your input on this is valuable.

**Comment by AndyCGYan** [comment]
No follow-up in 2 weeks, closing.
