### ISSUE TITLE
Resolve patch conflict

### ISSUE THREAD

**Issue by Jasuf** [AndyCGYan/lineage_build_unified#27]
After some time running the script I'm met with a patch conflict on "Applying change number 332083...". 

Conflict itself is trivial, and I can fix it no problem, but how do I keep my changes? They are discarded on the next script run and build fails again with the exact same error.

Alternatively, maybe there's a way to just discard this patch entirely? Doesn't look like something very important to me.

(In another similar issue you suggested to wait till next patches sync; I'd prefer to resolve this myself now, if possible)

**Comment by Jasuf** [comment]
To anyone who will encounter a similar problem: you can get around this by changing a line in `buildbot_unified.sh` script to:

```
repopick -Q "(status:open+NOT+is:wip)+project:LineageOS/android_packages_apps_Trebuchet+branch:lineage-19.1" -e 332083
```
Where `332083` is a number of problematic change. `-e` is an `--exclude` option, o it removes this change from the bulk added by previous monstrous expression.

**Comment by AndyCGYan** [comment]
Feel free to exclude patches, or if you'd like, exclude _and_ put your resolved one as a patch into `lineage_patches_unified` temporarily, so they still get applied.

BTW, that query will get even more "monstrous" next time I push, as I'll be excluding changes that have CR-* or V-* on them.
