### ISSUE TITLE
关于安卓10以来的Aosp原始镜像无法拨打电话的问题。

### ISSUE THREAD

**Issue by han4976** [AndyCGYan/lineage_build_unified#28]
大佬，这个问题如何修复呀？请求支援。

**Comment by AndyCGYan** [comment]
Quote the XDA thread:

> Must-read:
> You are STRONGLY ADVISED to try [PHH's AOSP](https://github.com/phhusson/treble_experimentations/releases) of equivalent version FIRST and identify/[report](https://github.com/phhusson/treble_experimentations/issues) issues there, before moving onto other GSIs that are based on his work, including this one.
> If you do find bugs on this GSI and want to report, then you MUST try reproducing on AOSP, and ONLY proceed to report here when it's specific to this GSI. This filters out bugs common to all PHH-based GSIs, which you should let PHH know, not me. I might silently ignore your report if you skip this.

---

引用XDA原帖：

> 必读：
> **强烈建议先**试用[PHH的AOSP](https://github.com/phhusson/treble_experimentations/releases)，并在其上探索/[报告](https://github.com/phhusson/treble_experimentations/issues)问题，之后再试用基于PHH的其他GSI，包括本GSI。
> 若在本GSI上发现问题，则**必须**先在AOSP上尝试复现，**只有**确定是本GSI特有问题（AOSP上无法复现）再报告。这样可以筛选出基于PHH的GSI共有的问题，这类问题应该报告给PHH而不是我。若跳过这些步骤，我有权无视报告。

**Comment by han4976** [comment]
哦哦，这个问题是源于谷歌Android开发者网站上，提供的并且是公开的实验性GSI系统镜像。而phh大神制作的AOSP10/11/12也一样有这样的情况发生。也就是使用GSI集成的电话功能通话时，将听不见任何语音。

**Comment by AndyCGYan** [comment]
Google GSI上同有的问题，我想PHH会有些兴趣；但另一方面，这个问题听着挺耳熟的，也许他早就解决了？
高通机型的话，先设置 - PHH Treble Settings - Use alternate audio policy试试？
