### ISSUE TITLE
关于“安全中心”这个管理警报，如何永久禁用/永久关闭？

### ISSUE THREAD

**Issue by han4976** [AndyCGYan/lineage_build_unified#29]
![Screenshot_20220613-204837_Trebuchet](https://user-images.githubusercontent.com/82552465/173425286-2516f4ba-66ca-4cbb-bda6-8df98c6e6844.png)

“安全中心”这个管理警报，在每次刷机后首次开机时，均会在联网的第一时间自动跳出来提醒签名不是最新的，或者签名已过期。
有没有什么办法让它永远不会自动提醒？

**Comment by han4976** [comment]
![Screenshot_20220614-032616](https://user-images.githubusercontent.com/82552465/173429607-f3cd3dcb-5000-4225-83b6-6eb2860c45cd.png)

**Comment by AndyCGYan** [comment]
长按下通知？

**Comment by han4976** [comment]
我的想法是，有木有办法让它再恢复出厂设置后也不会再出现。

**Comment by AndyCGYan** [comment]
> 下次恢复出厂设置后，永远也不会再出现

不可能。
