### ISSUE TITLE
建议构建一个Non-su系统镜像

### ISSUE THREAD

**Issue by han4976** [AndyCGYan/lineage_build_unified#31]
自从 AOSP 12版本开始，Phhusson已经陆续发布了各种Non-su版本的GSI镜像。但是由于他制作的镜像存在汉化不完整，和系统时间错误的问题。我建议AndyYan先生为大家构建一个Vanilla的No-su版本。这也是许多人的愿望希望AndyYan先生能够做出这一系统版本。

**Comment by AndyCGYan** [comment]
出于编译时间以及上传数据量（带宽）的考虑，我将提供的版本数量控制在10个以内，且尽量减少不必要的版本数量。

- 提供非SU版本将直接导致版本数量翻倍。
- 32*（arm32）和A64*（arm32_binder64）的存在大大增加了版本数量，挤压其他版本（包括GAPPS在内）的存在空间。
- 安卓10期间我发起了在*S和*N之间二选一的XDA投票，结果是*S胜出。
- SU版本大大方便了GSI不开机等情况下的debug操作。
- 完全可以自行在PHH设置中选择Securize，或通过[sas-creator](https://github.com/AndyCGYan/sas-creator)生成非SU版本，且与原版的差别远小于VNDKLite版本，在我看来属于“不必要的版本”。

综上，在情况有较大改观前，不接受对此问题的进一步讨论，谢谢。

**Comment by han4976** [comment]
我认为，纯arm32版本可以从安卓12开始移除了，

**Comment by AndyCGYan** [comment]
> 我认为，纯arm32版本可以从安卓12开始移除了，

32*已死，但A64*还在…
