### ISSUE TITLE
Enable call recording?

### ISSUE THREAD

**Issue by Peque** [AndyCGYan/lineage_build_unified#35]
LOS has a built-in call recording feature that seems to be disabled in this build.

Could it be enabled? :blush:

**Comment by AndyCGYan** [comment]
I can try adding in the config, but just so you know, it's also controlled by region to conform with local laws, and I won't work around that.

**Comment by Peque** [comment]
Thanks @AndyCGYan! :rocket:

**Comment by AndyCGYan** [comment]
Added in October update (should be uploaded soon).
