### ISSUE TITLE
Compatibility with SavetyNet

### ISSUE THREAD

**Issue by snoweuph** [AndyCGYan/lineage_build_unified#38]
I dont know if this hre is the right place to ask, if not sry, please tell me where I should ask if you know it.

I want to make my phone work degooglet, but want to pass savetyNet Basic atleast.

Im owning a moto g8 plus which isnt officaly supporte for LOS, thats why I tryed this build https://sourceforge.net/projects/andyyan-gsi/files/

im using the 19 arm64 bvs build. the rom works great, but I cant pass SavetyNet basic with it.
So here comes my question: is this rom savety nety compatible, and if not, would resigning the image maybe work (and if yes, where should I start to do that )?

**Comment by AndyCGYan** [comment]
A secure variant should have better chance; Magisk modules on that topic even more so.

Beyond these, I offer no further guarantee or guidance on GAPPS/SafetyNet, as I'm in China and I don't use / can't verify those.

**Comment by snoweuph** [comment]
ahh okay, thx for the info
