### ISSUE TITLE
Broken Google Services.

### ISSUE THREAD

**Issue by tangymc** [AndyCGYan/lineage_build_unified#40]
Hi! It seems that Google services is broken in lineage-20.0-20230115-UNOFFICIAL-a64_bgN. Google Play Store doesn't seem to be installed, Even apps such as Chrome and GMail doesn't detect Google Play Services even if it's there.

Google Services Framework and some other Google stuff is also crashing.

The device I'm running it on [Samsung Galaxy A02s](https://github.com/phhusson/treble_experimentations/wiki/Samsung#:~:text=arm64-,Samsung%20Galaxy%20A02s,-a02s)

**Comment by AndyCGYan** [comment]
It seems to be because arm64 GAPPS was included even in A64*. Weird this had only been brought up until now - I've been building like so for months by now.

A64* devices are all "legacy" by my standards, and I haven't had one in years, so I can't test them myself. I might require your help when I get to do a test build.

**Comment by tangymc** [comment]
I was confused when I saw the arm64 GApps. I think it's also the same issue for Lineage 19.1.

**Comment by tangymc** [comment]
> I was confused when I saw the arm64 GApps. I think Lineage 19.1 also have the same issue.

Nope, Lineage 19.1 seems to have a proper GApps integration.

**Comment by AndyCGYan** [comment]
> Nope, Lineage 19.1 seems to have a proper GApps integration. So, It's only for Lineage 20.

Correct, I've only switched to MindTheGapps since 20, and that's when I made the mistake.

Good to know that you're still watching this, I guess that means you're ready for testing - I'm building one as we speak.

**Comment by AndyCGYan** [comment]
Done, please test.
https://sourceforge.net/projects/andyyan-gsi/files/Testing/

**Comment by tangymc** [comment]
Working as expected! All is good!

**Comment by tangymc** [comment]
I also have a question regarding the charging animation (when the phone is turned on) on the GSI. Shouldn't it show the percentage when showing the animation? Like, when you plug it in, in the animation, it should show the percentage but instead do this : 

https://user-images.githubusercontent.com/74885686/227717255-e23505d2-f448-40f4-a3dd-877a021cfd16.mp4

**Comment by AndyCGYan** [comment]
> Shouldn't it show the battery percentage in the animation? (It's same in other lineage builds)

No? Since when? This is AOSP behaviour.

As the original issue has now been resolved, closing this now. Feel free to continue the discussion though.
