### ISSUE TITLE
App broke with last update

### ISSUE THREAD

**Issue by RogerioTDS** [AndyCGYan/lineage_build_unified#42]
Hello, sorry for the inconvenience.
I don't know if this is the right place but I'm posting it here.
I've been using the GSI since its launch, October 2022, but this latest update - on May 6, 2023, broke this application:

https://play.google.com/store/apps/details?id=br.com.original.bank&hl=pt_BR&gl=US&pli=1

It worked fine before. How would you fix it?
I'm using the light version, android 13!

**Comment by AndyCGYan** [comment]
Unfortunately, given my geological location, if the app depends on either GAPPS/GMS or actually having a bank account, I won't be able to look into it. Please describe the breakage in more detail and confirm what one needs to replicate it (esp. the above dependencies).

**Comment by RogerioTDS** [comment]
Hello, thanks for the reply!
I changed the GSI from the "Light" version to the "TD" version but the problem persists.
It's with gapps and you need an account, so I don't think you'll be able to...
Well, I sent a bug report to the app developer.
I'll leave the prints here too, in case it helps, because I couldn't generate a text file, in case it helps with anything.
Because I can't use this app anymore.
![1](https://github.com/AndyCGYan/lineage_build_unified/assets/120617835/d3519d89-ab02-408a-bfed-e667e0eaee88)
![2](https://github.com/AndyCGYan/lineage_build_unified/assets/120617835/3d001222-d251-4d64-ad6e-826154ab1fd7)

![3](https://github.com/AndyCGYan/lineage_build_unified/assets/120617835/dd017f15-e683-4a9e-937e-85210107c5c6)
![4](https://github.com/AndyCGYan/lineage_build_unified/assets/120617835/31c59a28-0a61-42f3-ab42-633eaf93b6a1)
![5](https://github.com/AndyCGYan/lineage_build_unified/assets/120617835/3d1a6e0f-f61d-4aa2-8bbd-72d5452d362b)
![6](https://github.com/AndyCGYan/lineage_build_unified/assets/120617835/5246dbea-d149-4b86-97e0-84f7927805ce)
![7](https://github.com/AndyCGYan/lineage_build_unified/assets/120617835/a34f66d5-edd4-4751-9f8a-2a4d87018208)
![8](https://github.com/AndyCGYan/lineage_build_unified/assets/120617835/76f0eef9-b2ff-4338-a677-548605521224)

**Comment by AndyCGYan** [comment]
Closing this as it seems non-actionable for now.
