### ISSUE TITLE
Bugs with earpiece speaker on POCO M4 Pro

### ISSUE THREAD

**Issue by Sabuntu** [AndyCGYan/lineage_build_unified#44]
When talking, you can hear your echo, and after that a squeaky sound.

**Comment by Sabuntu** [comment]
Don't know if this is the right place, I'm using Pixel Experience Plus GSI.

**Comment by AndyCGYan** [comment]
> Don't know if this is the right place, I'm using Pixel Experience Plus GSI.

Report to ponces, he has his own repos / release page / Telegram group.
