### ISSUE TITLE
Swipe fingerprint for notifications works backwards when in landscape.

### ISSUE THREAD

**Issue by SowTag** [AndyCGYan/lineage_build_unified#45]
If you turn on Swipe fingerprint for notifications it does work, but if you switch to landscape (aka tilt the device 90°) the behavior is reversed.

On portrait, swiping down pulls down the notification shade.
On landscape, swiping down does nothing, but swiping up opens the notification shade. The gesture behaves backwards, if the shade is already open swiping down (which should expand QS) closes the shade and swiping up (which should close the shade) expands QS.

On TrebleDroid AOSP builds, the gesture does not flip, it remains the same: you need to swipe left or right to open or close the shade depending on the orientation of the device, in other words, it works exactly the same as in portrait. My suspicion is that Lineage or this build specifically has some kind of patch that tries to add this functionality of rotating the gesture when the screen is not on portrait.

Device is motorola one fusion, 4GB RAM, Snapdragon 710. Came with Android Q, latest OEM update got it to Android R/11.

**Comment by AndyCGYan** [comment]
Thanks for isolating this on TD-AOSP first, and providing a reasonable speculation - it might indeed be an LOS upstream platform-side change. I don't have any device to debug this on myself, though, so understand I'll have to deprioritize this (but leave it open) for now.

**Comment by AndyCGYan** [comment]
As I only intended GitHub to host code, I'm scrubbing all open issues and closing the Issues section.

If you have an unresolved issue, please move to XDA, but do follow appropriate reporting procedures (most importantly, test on TD-AOSP in parallel).
