### ISSUE TITLE
Wired headphones on Samsung A10 do not get detected

### ISSUE THREAD

**Issue by MohammedMehdiTBER** [AndyCGYan/lineage_build_unified#46]
Despite trying:
`adb shell setprop persist.sys.overlay.devinputjack true`

I still can't get the headphones to work in 3.5mm jack

**Comment by userxinsane** [comment]
is it possible to use this toggle to disable headphone mode and also do I need to root?

**Comment by AndyCGYan** [comment]
Canned response from the XDA thread:

> MUST-READ - reporting bugs:
> 
> If you want to report a bug, then you MUST try reproducing on an AOSP reference build of around the same date from [TrebleDroid](https://github.com/TrebleDroid/treble_experimentations/releases), and ONLY proceed to report here when it's specific to this GSI. This filters out bugs common to all TD-based GSIs, which you should still let me know, but it might not be mine to fix. I might silently ignore your report if you skip this.

**Comment by AndyCGYan** [comment]
As I only intended GitHub to host code, I'm scrubbing all open issues and closing the Issues section.

If you have an unresolved issue, please move to XDA, but do follow appropriate reporting procedures (most importantly, test on TD-AOSP in parallel).
