### ISSUE TITLE
How long will you support LineageOS 19.1 

### ISSUE THREAD

**Issue by Artem13327** [AndyCGYan/lineage_build_unified#48]
The fact is that there is a problem with Android 13 GSI on my device that has not yet been completely fixed. And I want to know how long I will be getting security patches for LineageOS 19.1 GSI

**Comment by AndyCGYan** [comment]
Rule #1 from the LineageOS subreddit also applies here:

> Do not ask for an ETA
> 
> Don't ask for the estimate time of arrival of builds for a device. Builds will come when ready. Don't ask about future plans, updates, developments, or news. We don't have crystal balls, schedules, or grand strategies that dictate when or if things will happen.

As of now, LOS19 has been moved to quarterly build mode.
