### ISSUE TITLE
Adding system files during build time

### ISSUE THREAD

**Issue by Anubiska** [AndyCGYan/lineage_build_unified#50]
Hello, is it possible to add two system files that need to be in /system/framework and /system/etc/permissions of the final image, before or during the build?

Thanks so much!

**Comment by waltercool** [comment]
Yes

**Comment by Anubiska** [comment]
**Issue**: Copying files to /data/data or /data/media during build so they're visible to AOSP File Manager after boot.

**Documented Solution**: 
- I first copied the files folder to /system during build with: `PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,files_folder,system/files_folder)` (this works)
- Then I copy a file from /system/files_folder to /data/data or /data/media by adding this to `system/core/rootdir/init.rc` in the post-fs-data section: `copy /system/files_folder/file.txt /data/media/file.txt` (this works too)
- With a root file explorer I can see the files are copied correctly, but don't show up in AOSP File Manager at `Android/data` , `Android/media` or `Android/obb`

**Issue 1.1**: Installing APK (Magisk App) to /data during build:

**Documented Solution:**
- Adding `LOCAL_MODULE_PATH := $(TARGET_OUT_DATA)` to the Android.mk of the app
- After adding the above code, the app is not visible in the launcher, and no install files can be found anywhere. (Without the LOCAL_MODULE_PATH line it installs fine in /system)
 
Thank you so much. I would like to donate to your cause, is there a BTC address or coffee button?
```

**Comment by AndyCGYan** [comment]
- If you wish to add to `/system`, I suggest Magisk + [MMT-Extended](https://github.com/Zackptg5/MMT-Extended).
- I believe `TARGET_OUT_DATA` builds to a standalone data image in the build artifact, but as we only flash the system image, changes there are omitted.
- `/data` != `/sdcard/Android/data`
- I came late and didn't help with your issues here, but if you so wish, [PayPal](https://paypal.me/AndyCGYan)
