### ISSUE TITLE
Build fails during Soong process

### ISSUE THREAD

**Issue by waltercool** [AndyCGYan/lineage_build_unified#56]
Any idea how to resolve this problem? Running buildbot_unified.sh from lineage-20-td branch. Already tried my best to find what causes this and maybe someone have a lead for it.

`out/soong/make_vars-lineage_arm64_bvN.mk:1279: warning: JAVAC does not match between Make and Soong:
out/soong/make_vars-lineage_arm64_bvN.mk:1279: warning: Make : /etc/java-config-2/current-system-vm/bin/javac
out/soong/make_vars-lineage_arm64_bvN.mk:1279: warning: Soong: prebuilts/jdk/jdk11/linux-x86/bin/javac -J-XX:OnError="cat hs_err_pid%p.log" -J-XX:CICompilerCount=6 -J-XX:+UseDynamicNumberOfGCThreads -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1
out/soong/make_vars-lineage_arm64_bvN.mk:1306: warning: LEX does not match between Make and Soong:
out/soong/make_vars-lineage_arm64_bvN.mk:1306: warning: Make : flex
out/soong/make_vars-lineage_arm64_bvN.mk:1306: warning: Soong: out/soong/.intermediates/prebuilts/build-tools/flex/linux_glibc_x86_64/flex
In file included from build/make/core/cleanbuild.mk:30:
out/soong/make_vars-lineage_arm64_bvN.mk:1646: error: Soong variable check failed.
10:16:08 ckati failed with: exit status 1

!!! An error happened during script execution
!!! Please check console output for bad sync,
!!! failed patch application, etc.
`

Best regards

**Comment by waltercool** [comment]
Same for lineage-20-light

**Comment by AndyCGYan** [comment]
As I only intended GitHub to host code, I'm scrubbing all open issues and closing the Issues section.

If you have an unresolved issue, please move to XDA, but do follow appropriate reporting procedures (most importantly, test on TD-AOSP in parallel).
