### ISSUE TITLE
[Issue] Samsung Galaxy A12(Exynos Variant) Can't Receive Calls and Proximity Sensors dont work

### ISSUE THREAD

**Issue by SUFandom** [AndyCGYan/lineage_build_unified#57]
Lineage 20, with GApps, cannot receive calls, however calling someone can

Proximity sensors also dont work, so that means it cant turn off the display when calling via an earpiece handset

**Comment by AndyCGYan** [comment]
As I only intended GitHub to host code, I'm scrubbing all open issues and closing the Issues section.

If you have an unresolved issue, please move to XDA, but do follow appropriate reporting procedures (most importantly, test on TD-AOSP in parallel).
