### ISSUE TITLE
Boot fail on Galaxy Tab S8

### ISSUE THREAD

**Issue by jrapf32** [AndyCGYan/lineage_build_unified#59]
12-14 16:12:38.854  2470  2470 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
12-14 16:12:38.854  2470  2470 E AndroidRuntime: java.lang.RuntimeException: Failed to start service com.android.server.biometrics.AuthService: onStart threw an exception
12-14 16:12:38.854  2470  2470 E AndroidRuntime: 	at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:260)
12-14 16:12:38.854  2470  2470 E AndroidRuntime: 	at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:236)
12-14 16:12:38.854  2470  2470 E AndroidRuntime: 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:2474)
12-14 16:12:38.854  2470  2470 E AndroidRuntime: 	at com.android.server.SystemServer.run(SystemServer.java:940)
12-14 16:12:38.854  2470  2470 E AndroidRuntime: 	at com.android.server.SystemServer.main(SystemServer.java:650)
12-14 16:12:38.854  2470  2470 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-14 16:12:38.854  2470  2470 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-14 16:12:38.854  2470  2470 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:914)
12-14 16:12:38.854  2470  2470 E AndroidRuntime: Caused by: java.lang.NumberFormatException: For input string: "${fps_position}"
12-14 16:12:38.854  2470  2470 E AndroidRuntime: 	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
12-14 16:12:38.854  2470  2470 E AndroidRuntime: 	at jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
12-14 16:12:38.854  2470  2470 E AndroidRuntime: 	at java.lang.Float.parseFloat(Float.java:455)
12-14 16:12:38.854  2470  2470 E AndroidRuntime: 	at com.android.server.biometrics.AuthService.dynamicUdfpsProps(AuthService.java:920)
12-14 16:12:38.854  2470  2470 E AndroidRuntime: 	at com.android.server.biometrics.AuthService.getHidlFingerprintSensorProps(AuthService.java:1001)
12-14 16:12:38.854  2470  2470 E AndroidRuntime: 	at com.android.server.biometrics.AuthService.registerAuthenticators(AuthService.java:822)
12-14 16:12:38.854  2470  2470 E AndroidRuntime: 	at com.android.server.biometrics.AuthService.onStart(AuthService.java:674)
12-14 16:12:38.854  2470  2470 E AndroidRuntime: 	at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:258)
12-14 16:12:38.854  2470  2470 E AndroidRuntime: 	... 7 more

**Comment by AndyCGYan** [comment]
As I only intended GitHub to host code, I'm scrubbing all open issues and closing the Issues section.

If you have an unresolved issue, please move to XDA, but do follow appropriate reporting procedures (most importantly, test on TD-AOSP in parallel).
