### ISSUE TITLE
Need a manifest for assembly android TV

### ISSUE THREAD

**Issue by D042888-2** [AndyCGYan/lineage_build_unified#61]
Hello! Can you give me a manifest.xml file that remains after the firmware? It is needed from Lineage 20.0 td which on Android_13.0.0_R41

**Comment by D042888-2** [comment]
> Hello! Can you give me a manifest.xml file that remains after the firmware? It is needed from Lineage 20.0 td which on Android_13.0.0_R41

**Comment by AndyCGYan** [comment]
I've never offered ATV builds. It seems non-trivial to bring up, and last time I did, I was unable to boot/test it on phones. The userbase also seems so small that there were only 2 mentions over 5 years of building GSIs.
