### ISSUE TITLE
Applying patch group patches_treble Failed

### ISSUE THREAD

**Issue by GuanU244** [AndyCGYan/lineage_build_unified#64]
command:
```bash
bash lineage_build_unified/buildbot_unified.sh treble 64GN
```
error:
```bash
Applying patch group patches_treble
~/lineage-21-build-td/build/make ~/lineage-21-build-td
HEAD is now at c4d01858d2 build: Remove llkd
Applying: Remove init.vndk-nodef.rc
~/lineage-21-build-td
~/lineage-21-build-td/device/phh/treble ~/lineage-21-build-td
HEAD is now at 28781bb Give a persist prop to disable gl backpressure
Applying: treble: Lineage-ify
Applying: treble: Set BOARD_EXT4_SHARE_DUP_BLOCKS explicitly
Applying: treble: Set TARGET_NO_KERNEL_OVERRIDE
Applying: treble: Enable call recording
Applying: treble: Switch to MindTheGapps
Applying: treble: Stop securing ADB
Applying: treble: Securize on-demand
Applying: treble: Also use /data/adb for securize status
Applying: treble: Import prebuilt PHH Superuser
~/lineage-21-build-td
~/lineage-21-build-td/system/core ~/lineage-21-build-td
HEAD is now at d5994fd41 When setting ro.apex.updatable, actually set the value
Applying: Restore /sbin for Magisk compatibility
~/lineage-21-build-td
~/lineage-21-build-td/vendor/hardware_overlay ~/lineage-21-build-td
HEAD is now at 4717405 Merge pull request #89 from ildar/pie
error: the patch applies to 'TrebleApp/app.apk' (9125a527775bee8867e8d1b2d3ad0487d49d3a2f), which does not match the current contents.
error: TrebleApp/app.apk: patch does not apply
Failed applying /home/guanu/lineage-21-build-td/lineage_patches_unified/patches_treble/vendor_hardware_overlay/0001-TEMP-Up-TrebleApp-to-20240216.patch
```

**Comment by DocMAX** [comment]
Same here

**Comment by LeOS-GSI** [comment]
> Same here

you can't use the patches 'blind'. Source code is changing. So if a patch fail, adjust it manually and create a new patch for it.

**Comment by GuanU244** [comment]
I don't understand what this patch does since it's just a bunch of binaries

I tried many ways to apply this patch to the current apk, but failed
I'm not sure if it's because the file is too big.

So I just deleted the patch and the compilation was successful.
The system is running fine so far, not sure what this will cause.

I think this patch just makes the application return to the old version. Can you tell me if there is any mistake in this understanding?

Or can you teach me how to make my own patch?

Thanks you

btw, English is not my mother tongue, please forgive me if there is any disrespect.

**Comment by AndyCGYan** [comment]
> I don't understand what this patch does since it's just a bunch of binaries

Basically what needs to be done is rebase [my fork of TrebleApp](https://github.com/AndyCGYan/treble_app/tree/simplify-securize) on top of the latest (just one extra change, should be trivial), build from it, and replace the one in v_h_o.

Since the one in v_h_o gets updated once in a while, conflicts will happen regularly. Not a very elegant way to do it, yes... I'll look into a way to automate this.

> The system is running fine so far, not sure what this will cause.

Without it the securize feature in TrebleApp wouldn't work correctly. If you don't use it then you don't lose anything.
