### ISSUE TITLE
Haptic feedback on hardware keys not working

### ISSUE THREAD

**Issue by DocMAX** [AndyCGYan/lineage_build_unified#65]
Opening this issue as the haptic feedback is not working on my touch buttons. Stock android works as also other GSI works (peter_gsi_arm64_20230822.img)

As mentioned here it needs some kind of overlay.
https://xdaforums.com/t/gsi-13-lineageos-20-trebledroid-based.4517345/page-52#post-89371426

My phone is a Unihertz Jelly Star.

**Comment by DocMAX** [comment]
After some googling i found that for that to work we need some quirks to the ROM. See in https://gitea.angry.im/PeterGSI/android_device_peter_gsi especially the "init_gsi" part.

**Comment by AndyCGYan** [comment]
As I only intended GitHub to host code, I'm scrubbing all open issues and closing the Issues section.

If you have an unresolved issue, please move to XDA, but do follow appropriate reporting procedures (most importantly, test on TD-AOSP in parallel).
