### ISSUE TITLE
[FR] FlipFlap or folio_daemon

### ISSUE THREAD

**Issue by ildar** [AndyCGYan/lineage_build_unified#66]
service that turns on/off a tablet (or a phone) when a cover is opened/closed through a magnet/Hall sensor.
I suggest tablet users may miss it.
https://github.com/LineageOS/android_packages_apps_FlipFlap/

**Comment by ildar** [comment]
though LOS21 for some devices uses `folio_daemon`, e.g. https://github.com/LineageOS/android_device_samsung_gta4l-common/blob/lineage-21/folio-daemon/main.cpp

**Comment by AndyCGYan** [comment]
As I only intended GitHub to host code, I'm scrubbing all open issues and closing the Issues section.

If you have an unresolved issue, please move to XDA, but do follow appropriate reporting procedures (most importantly, test on TD-AOSP in parallel).
