### ISSUE TITLE
"reset factory data" loop

### ISSUE THREAD

**Issue by Maurice1502** [AndyCGYan/lineage_build_unified#68]
on your last GSI lineageOS 18.1 and with the non-SAR version, my device (bv9500) boot but immediatly go into "reset factory data" , i do so with my stock recovery.img and my device boot again and go  into the loop again 

does anyone have an idea on how to fix this?

**Comment by Subhashis2007** [comment]
Faced the same

**Comment by rusantiman** [comment]
I tried it on alldocube m8 (MediaTek Helio X27) and encountered the same problem.
But I was able to solve it.

This seems to occur if you haven't set a lock screen password. 
However, with our devices, we cannot set a password at first, so we need a strong countermeasure.
This assumes that AOSP 11.0 v313 can be started normally.

I will write the steps to solve the problem for my m8.
1.Decrypt with Disable_Dm-Verity_ForceEncrypt_11.02.2020.zip
2.Install AOSP 11.0 v313.
3. Launch and set lock screen password.
4.Dirty flush lineage 18.1.
Please do not format.

Note: It might just be my m8, but it automatically reboots the first time I start it. However, the second time it boots completely.

**Comment by AndyCGYan** [comment]
As I only intended GitHub to host code, I'm scrubbing all open issues and closing the Issues section.

If you have an unresolved issue, please move to XDA, but do follow appropriate reporting procedures (most importantly, test on TD-AOSP in parallel).
