### ISSUE TITLE
*** FATAL EXCEPTION IN SYSTEM PROCESS: main

### ISSUE THREAD

**Issue by rik0612c** [AndyCGYan/lineage_build_unified#70]
lineage-21.0-20240424-UNOFFICIAL-arm64_bvN.img.xz 
soft reboot after booted into lockscreen.
Device: motorola g9 power(cebu). flash gsi on the official A11.

log:

> 04-26 22:58:14.575  6831  6831 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
04-26 22:58:14.575  6831  6831 E AndroidRuntime: java.lang.IllegalStateException: Lost network stack. This is not the root cause of any issue, it is a side effect of a crash that happened earlier. Earlier logs should point to the actual issue.
04-26 22:58:14.575  6831  6831 E AndroidRuntime: 	at android.net.ConnectivityModuleConnector.maybeCrashWithTerribleFailure(ConnectivityModuleConnector.java:335)
04-26 22:58:14.575  6831  6831 E AndroidRuntime: 	at android.net.ConnectivityModuleConnector.-$$Nest$mmaybeCrashWithTerribleFailure(ConnectivityModuleConnector.java:0)
04-26 22:58:14.575  6831  6831 E AndroidRuntime: 	at android.net.ConnectivityModuleConnector$ModuleServiceConnection.onServiceDisconnected(ConnectivityModuleConnector.java:278)
04-26 22:58:14.575  6831  6831 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:2226)
04-26 22:58:14.575  6831  6831 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2241)
04-26 22:58:14.575  6831  6831 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:959)
04-26 22:58:14.575  6831  6831 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
04-26 22:58:14.575  6831  6831 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
04-26 22:58:14.575  6831  6831 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
04-26 22:58:14.575  6831  6831 E AndroidRuntime: 	at com.android.server.SystemServer.run(SystemServer.java:1005)
04-26 22:58:14.575  6831  6831 E AndroidRuntime: 	at com.android.server.SystemServer.main(SystemServer.java:689)
04-26 22:58:14.575  6831  6831 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-26 22:58:14.575  6831  6831 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
04-26 22:58:14.575  6831  6831 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:856)
04-26 22:58:14.848 10001 10001 E AndroidRuntime: FATAL EXCEPTION: main
04-26 22:58:14.848 10001 10001 E AndroidRuntime: PID: 10001
04-26 22:58:14.848 10001 10001 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause

**Comment by AndyCGYan** [comment]
As I only intended GitHub to host code, I'm scrubbing all open issues and closing the Issues section.

If you have an unresolved issue, please move to XDA, but do follow appropriate reporting procedures (most importantly, test on TD-AOSP in parallel).
