### ISSUE TITLE
How to open lineage updater in gsi

### ISSUE THREAD

**Issue by Lingchen218** [AndyCGYan/lineage_build_unified#71]
After I built the system.img and flashed it into the phone, I didn’t see update.apk.

**Comment by LeOS-GSI** [comment]
For what do you need a a update.apk ? The system.img is your update

**Comment by Lingchen218** [comment]
I want to update the system through this updater. I saw that lineage has this updater.apk, but I couldn’t find it after flashing into the system.

> For what do you need a a update.apk ? The system.img is your update
> 
> For a GSI there is no OTA. Flashing GSI is the update job

**Comment by Lingchen218** [comment]
<img width="712" alt="2dd057db92de55a6cd5822fb19d2831" src="https://github.com/AndyCGYan/lineage_build_unified/assets/48959004/e687b552-d9fb-4e90-877f-83532fab300f">

**Comment by Lingchen218** [comment]
Yes, it's updating system.img

> For what do you need a a update.apk ? The system.img is your update
> 
> For a GSI there is no OTA. Flashing GSI is the update job

**Comment by LeOS-GSI** [comment]
> I want to update the system through this updater. I saw that lineage has this updater.apk, but I couldn’t find it after flashing into the system.
> 
> > For what do you need a a update.apk ? The system.img is your update
> > For a GSI there is no OTA. Flashing GSI is the update job

as far as I know, this update app is used for rom OTA update and has nothing to do with GSI updates

**Comment by Lingchen218** [comment]
> > I want to update the system through this updater. I saw that lineage has this updater.apk, but I couldn’t find it after flashing into the system.
> > > For what do you need a a update.apk ? The system.img is your update
> > > For a GSI there is no OTA. Flashing GSI is the update job
> 
> as far as I know, this update app is used for rom OTA update and has nothing to do with GSI updates

Yes, I just want to use this program to update ROM OTA

**Comment by Lingchen218** [comment]
> But you have build a GSI (system.img) not a rom. There is a big difference between GSI and Rom
Yes, I know, Rom contains some more stuff, is there any way to enable this updater program?

**Comment by LeOS-GSI** [comment]
> > But you have build a GSI (system.img) not a rom. There is a big difference between GSI and Rom
> > Yes, I know, Rom contains some more stuff, is there any way to enable this updater program?

no, there isn't. PHH and Ponces for example have a OTA server and a script included in their GSI to make a OTA update. But that is only working on devices with super partiton

**Comment by AndyCGYan** [comment]
Updater/OTA will NOT be considered.

- Magisk compatibility
- User awareness/vigilance when updating
