### ISSUE TITLE
Cramped buttons

### ISSUE THREAD

**Issue by Emirhan01031** [AndyCGYan/lineage_build_unified#74]
![Screenshot_20240518-182208_Dosyalar.png](https://github.com/AndyCGYan/lineage_build_unified/assets/159832793/1bb4654e-4012-4599-9319-f09acb44fe63)

**Comment by AndyCGYan** [comment]
Looks like your vendor has some sort of overlay that changes QS column count - an option in TrebleApp that disables vendor overlay might help.

**Comment by AndyCGYan** [comment]
As I only intended GitHub to host code, I'm scrubbing all open issues and closing the Issues section.

If you have an unresolved issue, please move to XDA, but do follow appropriate reporting procedures (most importantly, test on TD-AOSP in parallel).

**Comment by Emirhan01031** [comment]
I can't find Disable Vendor Overlay option in phh?

**Comment by AndyCGYan** [comment]
Sorry, double-checked, it's not a toggle but a shell command: `setprop persist.sys.phh.no_vendor_overlay true` - set and reboot.

Even if you're on an unrooted variant, "Rooted debugging" in Dev options should allow getting a rooted shell, for setting this.
