### ISSUE TITLE
Build results in bootloop while binary runs fine

### ISSUE THREAD

**Issue by bob2356** [AndyCGYan/lineage_build_unified#75]
My Unihertz Jelly Star works fine with lineage-20.0-20240516-UNOFFICIAL-arm64_bvN.img.xz from https://sourceforge.net/projects/andyyan-gsi/files/lineage-20-td. When I try to build the same using the build script, my binary is about 32 kB larger and phone ends in a boot loop. What am I doing wrong?

I start from a fresh installed Ubuntu 23.10.1 + update/upgrade/reboot.

I install the tools as given in the lineageos wiki:

```
#!/bin/bash -x

wget https://dl.google.com/android/repository/platform-tools-latest-linux.zip
unzip platform-tools-latest-linux.zip -d ~
echo -e "\n# add Android SDK platform tools to path\nif [ -d \"$HOME/platform-tools\" ] ; then\n\tPATH=\"$HOME/platform-tools:$PATH\"\nfi\n" >> ~/.profile
source ~/.profile

sudo apt-get -y install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev

wget http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.4-2_amd64.deb && sudo dpkg -i libtinfo5_6.4-2_amd64.deb && rm -f libtinfo5_6.4-2_amd64.deb
wget http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libncurses5_6.4-2_amd64.deb && sudo dpkg -i libncurses5_6.4-2_amd64.deb && rm -f libncurses5_6.4-2_amd64.deb

sudo apt-get -y install python-is-python3

mkdir -p ~/bin
curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
chmod a+x ~/bin/repo
echo -e "\n# set PATH so it includes user's private bin if it exists\nif [ -d \"$HOME/bin\" ] ; then\n\tPATH=\"$HOME/bin:$PATH\"\nfi\n" >> ~/.profile
source ~/.profile

git config --global user.email "invalid@invalid.invalid"
git config --global user.name "bob"
git lfs install
git config --global trailer.changeid.key "Change-Id"

sudo apt-get -y install openjdk-11-jdk
```

Please note, despite the wiki says "LineageOS 18.1+: OpenJDK 11 (included in source download)" I manually install openjdk-11-jdk. Otherwise I'll get "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."

After this, I run the commands:

```
#!/bin/bash -x

source ~/.profile
mkdir lineage-20-build-td; cd lineage-20-build-td
repo init -u https://github.com/LineageOS/android.git -b lineage-20.0 --git-lfs
git clone https://github.com/AndyCGYan/lineage_build_unified lineage_build_unified -b lineage-20-td
git clone https://github.com/AndyCGYan/lineage_patches_unified lineage_patches_unified -b lineage-20-td
bash lineage_build_unified/buildbot_unified.sh treble 64VN
```

The script runs fine, but as mentioned above, the generated binary does not work on my phone, while the same binary from your sourceforge works fine. Unfortunately, the complete shell output is about 3 MB large, so it's too large for here as well as for pastebin.

**Comment by AndyCGYan** [comment]
I do need to check the console output for some basics...

Considering visibility/privacy of the console log, plus I'm closing down the Issues section soon, I suggest continuing this topic over at XDA in private ("Start a conversation").

**Comment by AndyCGYan** [comment]
Continuing over at XDA, closing.
